name: Scheduled Tasks

on:
  schedule:
    # Runs every 5 minutes for testing
    - cron: "*/5 * * * *"
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run monitoring check
        run: node scripts/update-data.js

      # Add step to commit and push the log file
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add scripts/cron-test.log
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update cron test log [skip ci]" && git push)
