name: Scheduled Tasks

on:
  schedule:
    # Runs every 5 minutes for testing
    - cron: "*/5 * * * *"
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: List directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory structure:"
          ls -R

      - name: Run monitoring check
        run: node scripts/update-data.js
